// <auto-generated />
namespace MVC5UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitMVC5UI_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitMVC5UI_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201708140742189_InitMVC5UI_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
